#!/bin/bash

# SSL_DOMAIN
# SSL_EMAIL

if [ -z "$SSL_DOMAIN" ] || [ -z "$SSL_EMAIL" ]; then

    echo "You need the SSL_DOMAIN and the SSL_EMAIL variables"

else

    /usr/bin/certbot --apache certonly -d $SSL_DOMAIN --email $SSL_EMAIL  --agree-tos --non-interactive

    sed -i "s/\/etc\/ssl\/certs\/ssl-cert-snakeoil.pem/\/etc\/letsencrypt\/live\/$SSL_DOMAIN\/fullchain.pem/g" /etc/apache2/sites-available/default-ssl.conf
    sed -i "s/\/etc\/ssl\/private\/ssl-cert-snakeoil.key/\/etc\/letsencrypt\/live\/$SSL_DOMAIN\/privkey.pem/g" /etc/apache2/sites-available/default-ssl.conf

    /usr/bin/supervisorctl restart apache

fi
